// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwyT-wr9hGgONcZBHUcNyJR5jmLsZvZc',
    appId: '1:1030759456130:web:83664b5479bc1731fd439b',
    messagingSenderId: '1030759456130',
    projectId: 'futsal-pay-6c54b',
    authDomain: 'futsal-pay-6c54b.firebaseapp.com',
    storageBucket: 'futsal-pay-6c54b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy5kI_cjoCxF7OgvaYIcGYaCXKln7hDr0',
    appId: '1:1030759456130:android:1171afa8c19b027cfd439b',
    messagingSenderId: '1030759456130',
    projectId: 'futsal-pay-6c54b',
    storageBucket: 'futsal-pay-6c54b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnM2LJogdciZvhfotL4znvQYpBnFNl0I8',
    appId: '1:1030759456130:ios:de33c849cf3f9c07fd439b',
    messagingSenderId: '1030759456130',
    projectId: 'futsal-pay-6c54b',
    storageBucket: 'futsal-pay-6c54b.firebasestorage.app',
    androidClientId: '1030759456130-455uc4446dq53m9mhomssqj0ududjfsn.apps.googleusercontent.com',
    iosClientId: '1030759456130-ocmskn5h5e0g585jicgg4jrsn3236rsf.apps.googleusercontent.com',
    iosBundleId: 'com.zenith.futsal.pay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnM2LJogdciZvhfotL4znvQYpBnFNl0I8',
    appId: '1:1030759456130:ios:e53dcc103fc12eaffd439b',
    messagingSenderId: '1030759456130',
    projectId: 'futsal-pay-6c54b',
    storageBucket: 'futsal-pay-6c54b.firebasestorage.app',
    iosBundleId: 'com.example.futsalpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQwyT-wr9hGgONcZBHUcNyJR5jmLsZvZc',
    appId: '1:1030759456130:web:8c9c4aa472b93b7afd439b',
    messagingSenderId: '1030759456130',
    projectId: 'futsal-pay-6c54b',
    authDomain: 'futsal-pay-6c54b.firebaseapp.com',
    storageBucket: 'futsal-pay-6c54b.firebasestorage.app',
  );
}