// <auto-generated />
using System;
using FutsalApi.Data.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FutsalApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103_FixReviewGroundIdType")]
    partial class FixReviewGroundIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Copy the entire model configuration from AppDbContextModelSnapshot
            // This is the full model state after the migration
            
#pragma warning restore 612, 618
        }
    }
}
